### ISSUE TITLE
Importação variável V0015

### ISSUE THREAD

**Issue by gdocesp** [cran/PNSIBGE#2]
Olá, gostaria de trabalhar com a variável V0015, que estão presentes no arquivo de microdados, mas quando utilizo a função pns_desgin estas observações desaparem. Tanto que o total da amostra diminui.

Já com a importação online os dados amostrais baixados também já excluem as obervações com respostas diferentes de "Realizada".

Tem alguma forma de trabalhar com estes dados e seus respectivos pesos para construção de amostra complexa?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Gabriel-Assuncao** [comment]
Bom dia.
Peço por gentileza que feche este 'issue' que foi aberto e faça a abertura através do repositório do mantenedor em https://github.com/Gabriel-Assuncao/PNSIBGE/issues ou entre em contato diretamente através do e-mail 'pacotesipd@ibge.gov.br' para que possamos atender à sua solicitação.

Good Morning.
I kindly ask you to close this 'issue' that was opened and open it through the maintainer's repository on https://github.com/Gabriel-Assuncao/PNSIBGE/issues or contact us directly via the email 'pacotesipd@ibge.gov.br' so that we can respond to your request.
